# cloudbuild.yaml
steps:
  # Step 1: Build the Docker container
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/elarafrontend'
      # Pass our variable directly to Docker's --build-arg flag
      # _NEXT_PUBLIC_BACKEND_API_URL is a user-defined substitution variable we will provide.
      - '--build-arg'
      - 'NEXT_PUBLIC_BACKEND_API_URL=${_NEXT_PUBLIC_BACKEND_API_URL}'
      - '.'
    id: 'Build'

  # Step 2: Push the container image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/elarafrontend'
    id: 'Push'

# This tells Cloud Build where to find the final image
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/elarafrontend'

# Note: Substitutions like $PROJECT_ID and $COMMIT_SHA are provided automatically by Cloud Build.